extends:
  - stylelint-config-twbs-bootstrap/scss
  - stylelint-prettier/recommended
rules:
  at-rule-empty-line-before:
    - always
    - except:
        - blockless-after-same-name-blockless
        - first-nested
      ignore:
        - after-comment
      ignoreAtRules:
        - else
  rule-empty-line-before:
    - always-multi-line
    - except:
        - first-nested
      ignore:
        - after-comment
  scss/dollar-variable-default:
    - true
    - ignore: local
