extends:
  - stylelint-config-twbs-bootstrap/scss
  - stylelint-prettier/recommended
rules:
  rule-empty-line-before:
    - always-multi-line
    - except:
        - first-nested
      ignore:
        - after-comment
